apiVersion: apps/v1
kind: Deployment
metadata:
  name: eassessment-ui
spec:
  selector:
    matchLabels:
      app: eassessment-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: eassessment-ui
        tier: eassessment-ui
    spec:
     containers:
     - name: eassessment-ui
       image: "shashimls276/eassessment-ui:latest"
       ports:
       - containerPort: 8080        

---
apiVersion: v1
kind: Service
metadata:
  name: eassessment-ui
  labels:
    app: eassessment-ui
spec:
  selector:
    app: eassessment-ui
  ports:
    - port: 80
      targetPort: 8082
  type: LoadBalancer