apiVersion: apps/v1
kind: Deployment
metadata:
  name: eassessmentui
spec:
  selector:
    matchLabels:
      app: eassessmentui
  replicas: 1
  template:
    metadata:
      labels:
        app: eassessmentui
        tier: eassessmentui
    spec:
     containers:
     - name: eassessmentui
       image: "shashimls276/Assessment-ui:latest"
       ports:
       - containerPort: 8080        

---
apiVersion: v1
kind: Service
metadata:
  name: eassessmentui
  labels:
    app: eassessmentui
spec:
  selector:
    app: eassessmentui
  ports:
    - port: 80
      targetPort: 8082
  type: LoadBalancer